export const brandsList = [
    {
        id: 1,
        src: "/brands/INDIAai_Logo.svg",
        alt: "IndiaAI Mission",
        width: 250,
        height: 100,
        link: "https://www.linkedin.com/posts/devanshparikh8_indiaai-anselfdynamics-ocellux-activity-7305201665794523136-8GPU?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB8M2AcBJ9RCw0gbAPww1RXYo-29Q3rbZzs",
    },
    {
        id: 2,
        src: "/brands/NSRCEL_main_logo.png",
        alt: "IIM Bangalore NSRCEL",
        width: 220,
        height: 50,
        link:"https://nsrcel.org/healthcare-incubation-program/",
    },
    {
        id: 3,
        src: "/brands/mit-solve.jpg",
        alt: "MIT Solve",
        width: 250,
        height: 100,
        link:"https://www.linkedin.com/posts/devanshparikh8_solvemit-mit-globalchallenge2022-activity-6940543216953745408-Blz-?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB8M2AcBJ9RCw0gbAPww1RXYo-29Q3rbZzs",
    },
    {
        id: 4,
        src: "/brands/dst_nidhi.png",
        alt: "NIDHI PRAYAS - Department of Science and Technology",
        width: 250,
        height: 200,
        link:"",
    },
    {
        id: 5,
        src: "/brands/msh-logo-1.png",
        alt: "NIDHI PRAYAS - Department of Science and Technology",
        width: 220,
        height: 22.081,
        link:"",
    },
    {
        id: 6,
        src: "/brands/i-hub.png",
        alt: "iHub - A Government of Gujarat Initiative",
        width: 220,
        height: 22.081,
        link:"",
    },
    {
        id: 7,
        src: "/brands/aic_gusec.png",
        alt: "Atal Innovation Center Gujarat University Startup And Entrepreneurship Council",
        width: 250,
        height: 29.446,
        link:"",
    },
    {
        id: 8,
        src: "/brands/iiphg-new-logo.png",
        alt: "Indian Institute of Public Health Gandhinagar TBI",
        width: 250,
        height: 29.446,
        link:"https://iiphgtbi.org/current-incubatees/",
    },
    {
        id: 9,
        src: "/brands/GU-GUSEC.png",
        alt: "Gujarat University Startup And Entrepreneurship Council",
        width: 250,
        height: 29.446,
        link:"https://www.linkedin.com/posts/devanshparikh8_iiphg-techcelerate-nstedb-activity-7014962461275512832-4LDS?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB8M2AcBJ9RCw0gbAPww1RXYo-29Q3rbZzs",
    },
    {
        id: 10,
        src: "/brands/ESC-LOGO-1.png",
        alt: " Electronics and Computer Software Export Promotion Council (ESC)",
        width: 250,
        height: 29.446,
        link:"https://www.linkedin.com/posts/esc-india_stpiindia-buildingthenextunicorn-startups-activity-6989900568748019712-4-o9?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB8M2AcBJ9RCw0gbAPww1RXYo-29Q3rbZzs",
    },
    {
        id: 11,
        src: "/brands/chunauti.jpg",
        alt: " Electronics and Computer Software Export Promotion Council (ESC)",
        width: 250,
        height: 29.446,
        link:"#",
    },
    {
        id: 12,
        src: "/brands/MIT-COVID-19-Challenge.svg",
        alt: " Electronics and Computer Software Export Promotion Council (ESC)",
        width: 250,
        height: 29.446,
        link:"https://www.linkedin.com/posts/devanshparikh8_hack4thefuture-activity-6731477832528211968-PWZx?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB8M2AcBJ9RCw0gbAPww1RXYo-29Q3rbZzs",
    },
    
]